HairSalon/Models/Client.cs
namespace HairSalon.Models
{
  public class Client
  {
    public int ClientId { get; set; }
    public string Name { get; set; }
    public string PhoneNumber { get; set; }
    public string Address { get; set; }
    public int StylistId { get; set; }
    public virtual Stylist Stylist { get; set; }
  }
}

HairSalon/Models/HairSalonContext.cs
using Microsoft.EntityFrameworkCore;

namespace HairSalon.Models
{
  public class HairSalonContext : DbContext
  {
    public virtual DbSet<Stylist> Stylists { get; set; }
    public DbSet<Client> Clients { get; set; }

    public HairSalonContext(DbContextOptions options) : base(options) { }

    protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
    {
      optionsBuilder.UseLazyLoadingProxies();
    }
  }
}

HairSalon/Models/Stylist.cs
using System.Collections.Generic;

namespace HairSalon.Models
{
  public class Stylist
  {
    public Stylist()
    {
      this.Clients = new HashSet<Client>();
    }

    public int StylistId { get; set; }
    public string Name { get; set; }
    public string Schedule { get; set; }
    public virtual ICollection<Client> Clients { get; set; }
  }
}

HairSalon/Controllers/ClientsController.cs
using Microsoft.EntityFrameworkCore;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.AspNetCore.Mvc;
using HairSalon.Models;
using System.Collections.Generic;
using System.Linq;

namespace HairSalon.Controllers
{
  public class ClientsController : Controller
  {
    private readonly HairSalonContext _db;

    public ClientsController(HairSalonContext db)
    {
      _db = db;
    }

    public ActionResult Index()
    {
      List<Client> model = _db.Clients.Include(client => client.Stylist).ToList();
      return View(model);
    }

    public ActionResult Create()
    {
      ViewBag.StylistId = new SelectList(_db.Stylists, "StylistId", "Name");
      return View();
    }

    [HttpPost]
    public ActionResult Create(Client client)
    {
      _db.Clients.Add(client);
      _db.SaveChanges();
      return RedirectToAction("Index");
    }
  }
}

HairSalon/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;

namespace HairSalon.Controllers
{
  public class HomeController : Controller
  {
    [HttpGet("/")]
    public ActionResult Index()
    {
      return View();
    }
  }
}

HairSalon/Controllers/StylistsController.cs
using Microsoft.EntityFrameworkCore;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.AspNetCore.Mvc;
using HairSalon.Models;
using System.Collections.Generic;
using System.Linq;

namespace HairSalon.Controllers
{
  public class StylistsController : Controller
  {
    private readonly HairSalonContext _db;

    public StylistsController(HairSalonContext db)
    {
      _db = db;
    }

    public ActionResult Index()
    {
      List<Stylist> model = _db.Stylists.ToList();
      return View(model);
    }

    public ActionResult Create()
    {
      return View();
    }

    [HttpPost]
    public ActionResult Create(Stylist stylist)
    {
      _db.Stylists.Add(stylist);
      _db.SaveChanges();
      return RedirectToAction("Index");
    }

    public ActionResult Details(int id)
    {
      ViewBag.StylistId = _db.Stylists.FirstOrDefault(stylist => stylist.StylistId == id);
      var newClient = _db.Clients.Where(client => client.StylistId == id).ToList();
      return View(newClient);
    }

    //[HttpPost, ActionName("Details")]
    public ActionResult Edit(int id)
    {
      ViewBag.StylistId = _db.Stylists.FirstOrDefault(stylist => stylist.StylistId == id);
      var newClient = _db.Clients.Where(client => client.StylistId == id).ToList();
      return View(newClient);
    }
  }
}

HairSalon/Views/Clients/Create.cshtml
@{
  Layout = "_Layout";
}

@model HairSalon.Models.Client

<h4>Add a new task</h4>

@using (Html.BeginForm())
{
  @Html.LabelFor(model => model.Name)
  @Html.TextBoxFor(model => model.Name)
  @Html.LabelFor(model => model.PhoneNumber)
  @Html.TextBoxFor(model => model.PhoneNumber)
  @Html.LabelFor(model => model.Address)
  @Html.TextBoxFor(model => model.Address)

  @Html.LabelFor(model => model.Stylist)
  @Html.DropDownList("StylistId")

  <input type="submit" value="Add new client" class="btn btn-default" />
}
<p>@Html.ActionLink("Show all clients", "Index")</p>

HairSalon/Views/Clients/Index.cshtml
@{
  Layout = "_Layout";
}

@using HairSalon.Models;
@model List<HairSalon.Models.Client>;

<h1>Clients</h1>

@if (@Model.Count == 0)
{
  <h3>No clients have been added yet!</h3>
} 

@foreach (Client client in Model)
{
  <li>@Html.ActionLink($"{client.Name}", "Details", new { id = client.ClientId }) | @client.Stylist.Name</li>
}

<p>@Html.ActionLink("Add new client", "Create")</p> <p>@Html.ActionLink("See all stylists", "Index", "Stylists")</p>

HairSalon/Views/Home/Index.cshtml
@{
  Layout = "_Layout";
}

<h1>Welcome to Your Salon Portal!</h1>

<p>@Html.ActionLink("See all clients", "Index", "Clients")</p> <p>@Html.ActionLink("See all stylists", "Index", "Stylists")</p>

HairSalon/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>My To-Do List!</title>
    <link rel='stylesheet' href='https://maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css'>
    <link rel="stylesheet" href="~/css/styles.css">
  </head>
  <body>
    @RenderBody()
  </body>
</html>

HairSalon/Views/Stylists/Create.cshtml
@{
  Layout = "_Layout";
}

@model HairSalon.Models.Stylist

<h4>Add a new task</h4>
@using (Html.BeginForm())
{
  @Html.LabelFor(model => model.Name)
  @Html.TextBoxFor(model => model.Name)

  @Html.LabelFor(model => model.Schedule)
  @Html.TextBoxFor(model => model.Schedule)
  <input type="submit" value="Add new stylist" />
}
<p>@Html.ActionLink("Show all stylists", "Index")</p>

HairSalon/Views/Stylists/Details.cshtml
@{
  Layout = "_Layout";
}

@using HairSalon.Models;
@model List<HairSalon.Models.Client>;

<h1>Stylist Information</h1>

<p>Name: @ViewBag.StylistId.Name</p>
<p>Schedule: @ViewBag.StylistId.Schedule</p>

<h4>Stylist Clients</h4>

@if (@Model.Count == 0)
{
  <p>This stylist has no clients at the moment</p>
} 

@foreach (Client client in Model)
{
  <li>@client.Name</li>
}

@* <p>@Html.ActionLink("Edit Category", "Edit", new { id = Model.CategoryId })</p>
<p>@Html.ActionLink("Delete Category", "Delete", new { id = Model.CategoryId })</p> *@

<p>@Html.ActionLink("Back to stylist list", "Index")</p>
<p>@Html.ActionLink("Home", "Index", "Home")</p>

HairSalon/Views/Stylists/Index.cshtml
@{
  Layout = "_Layout";
}

@using HairSalon.Models;

<h1>Stylists</h1>

@if (@Model.Count == 0)
{
  <h3>No stylists have been added yet!</h3>
} 

<ul>
  @foreach(Stylist stylist in Model)
  {
    <li>@Html.ActionLink($"{stylist.Name}", "Details", new { id = stylist.StylistId })</li>
  }
</ul>

<p>@Html.ActionLink("Add new stylist", "Create")</p>
<p>@Html.ActionLink("Home", "Index", "Home")</p>